name: Access Secrets Workflow

on:
  push:
    branches:
      - master  

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Declare Environment Variables
      env:
        ENCODEKEY: ${{ secrets.ENCODEKEY }}
        GMAILKEY: ${{ secrets.GMAILKEY }}
        ROOT_PASSWORD:  ${{ secrets.ROOT_PASSWORD}} 
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        CLOUDPASSWORD: ${{secrets.CLOUDPASSWORD}}
        CLOUDUSER: ${{secrets.CLOUDUSER}}
      run: echo "Environment variables set."
